- name: Install NFS
  yum: name=nfs-utils state=present

- name: Create {{ nfs_user }} 
  user: name={{ nfs_user }} uid={{ nfs_user_id }}

- name: Create {{ nfs_group }}
  group: name={{ nfs_group }} gid={{ nfs_group_id }}

- name: Configure NFS
  template: src=export.conf.j2 dest=/etc/export.conf
  notify: Restart nfs service

- name: Create NFS Server shared directory
  file: path={{ nfs_dir }} state=directory owner={{ nfs_user }} group={{ nfs_group }}

- name: Started NFS server
  service: name=nfs state=started enabled=yes
